### ISSUE TITLE
Unauthorized Request Exception in Artifact exchange URL

### ISSUE THREAD

**Issue by alexeyburak** [bitovi/github-actions-react-to-github-pages#12]
Hi! I have set up an error-free launch of action, but it is not clear where to view the running project. Is that `Artifact exchange URL` ? But if I click on this link, I get UnauthorizedRequestException
`{"$id":"1","innerException":null,"message":"The user 'System:PublicAccess;aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' is not authorized to access this resource.","typeName":"Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server","typeKey":"UnauthorizedRequestException","errorCode":0,"eventId":3000}
`

And why i have no deployements in pull request?
<img width="874" alt="Screenshot 2023-09-06 at 12 04 14 PM" src="https://github.com/bitovi/github-actions-react-to-github-pages/assets/88793366/f3ef71ad-8f29-41b5-8db7-9093d48327bd">

**Comment by LeoDiazL** [comment]
Closing the issue due to inactivity. Feel free to reopen the issue if needed.
