### ISSUE TITLE
404 for content 

### ISSUE THREAD

**Issue by Vico1993** [bitovi/github-actions-react-to-github-pages#13]
Hello ! 

I was testing your github action... and I got some 404 for my content 🤔 
I was wonderring if you had this kind of error before? 

My [repo](https://github.com/Vico1993/echo-gh-page)
link to the [github page](https://vico1993.github.io/echo-gh-page/)

I tried to also setup the GitHub action by myself... but always 404 ( with `upload-pages-artifact` and `deploy-pages` )

![Screenshot 2023-09-13 at 11 43 37 PM](https://github.com/bitovi/github-actions-react-to-github-pages/assets/10399281/03531398-e438-46b4-b572-7fdfd6aca36e)

**Comment by mickmcgrath13** [comment]
Hi @Vico1993. Your repo link also 404's for me (is it a private repo?).

Can you share your pipeline execution output?

**Comment by LeoDiazL** [comment]
Closing the issue due to inactivity. Feel free to reopen the issue if needed.
