### ISSUE TITLE
Custom working directory

### ISSUE THREAD

**Issue by renyuneyun** [bitovi/github-actions-react-to-github-pages#7]
Hi. Is there a way to set a custom working directory when using this workflow?

[This SO answer](https://stackoverflow.com/questions/58139175/running-actions-in-another-directory/63122434#63122434) points out a way, but it does not work well with the workflow, because the directory does not exist before workflow run.

**Comment by LeoDiazL** [comment]
Hi there @renyuneyun ! Thanks for opening up an issue with us! 

Let me know if I understood you correctly. 

You need to specify a path where the `npm ci` and the other build commands are going to be executed. Is that correct? 

Is the example below what you would like to set up?
```
- name: Clean temp directory
  run: rm -rf *
  working-directory: ./temp
```
If so, at the moment, we don't have a way to set the working-directory. But we can look up to implement this in the short term if needed. 

If you need more help from us, feel free to contact us through [Discord!](https://discord.gg/J7ejFsZnJ4)!

**Comment by mickmcgrath13** [comment]
@renyuneyun Is this still an issue?

You could also try something like `build_command: cd /some/path && npm run build`

**Comment by LeoDiazL** [comment]
Closing the issue due to inactivity. Feel free to reopen the issue if needed.

**Comment by thenick775** [comment]
Just bumping. I too would like this feature, especially for a monorepo setup where I typically sparse checkout only the required service!

Either that or just allowing for sparse checkouts might be nice 😎

**Comment by mickmcgrath13** [comment]
maybe something like this?
https://github.com/bitovi/github-actions-react-to-github-pages/pull/21

**Comment by mickmcgrath13** [comment]
@thenick775 and @renyuneyun mind giving it a go when you get a sec?  I put up the PR, but i've not had a chance to test it.

**Comment by LeoDiazL** [comment]
Hi @thenick775 and @renyuneyun! 

We have [this PR](https://github.com/bitovi/github-actions-react-to-github-pages/pull/21) that solves your request. We would love to see if you have any other inputs for us before this makes it to a release. 

Thanks again for your involvement!

**Comment by thenick775** [comment]
I'll try to get some eyes on this in the next few days, unless someone can beat me to it! 😎

**Comment by thenick775** [comment]
@LeoDiazL checked this out and the options look good, but is there a way we can make the default working directory the directory that has been checked out using the sparse checkout?

Really what I'm trying to avoid is having to specify both of these in addition to sparse checkout commands:
```
install_command: cd ./gbajs3 && npm ci
path: ./gbajs3/dist
```

Ex. https://github.com/thenick775/gbajs3/actions/runs/9120500576/job/25077970464

(I can't tell if the sparse checkout is working since I can't ls, but I bet it is, the directory for rpm ci/the dist path are probably not modified)

**Comment by LeoDiazL** [comment]
@thenick775 sorry for the late response. 

About the comment, would be nice, but there's a catch. 

```
 Do a sparse checkout on given patterns. Each pattern should be separated with new lines.
```

Adding that option might not apply to everybody. 

If you are reusing and would like to reduce the amount of variables to adjust, you could define an environment variable that helps define the three variables at the same time. (Docs about variables [here](https://docs.github.com/en/actions/learn-github-actions/variables) )

Or you could even wrap our action inside one of you own creation, doing this merge automatically. 

Let me know your thoughts, and if I can merge/close this. (once that's done a new release will follow).

Leo

**Comment by thenick775** [comment]
That is a very fair point!

This definitely saves me enough with allowing for integrated sparse checkouts, I'm happy to close!
